### ISSUE TITLE
pakketten online bijles

### ISSUE THREAD

**Issue by blackshadev** [robinklaassen/aas2#80]
# TODOs
- [x] Meerdere pakketten met uren en bijles, invulling volgt. Alleen prijs en omschrijving is voor ons van belang
- [x] Apart type event voor online-bijles over periode
- [x] Aparte entiteit voor online bijles pakketten: event_sub_products
 -  velden: Naam, omschrijving, prijs, type
- [x] Binding tussen event en bijles pakketten in de participant pivot
- [x] Inschrijf formulier aanpassen met pakket keuzen voor online bijles, 
  - [x] Extra opmerkingen?
- [x] Bestaande deelnemers inschrijf formulier aanpassen voor online bijles
- [x] Event show aanpassen voor weergeven extra informatie (paketten)
- [x] IDeal traject checken, of bijles pakketten  wel worden door berekend  wordt en wordt gemarkeert als betaald.
- [x] Event index aanpassen om nieuwe event type weer te geven

## Aannames
- Korting gebaseerd op bestaande discount tabel

## Testen
- [x] Test aanmaken event
- [x] Test nieuwe inschrijving
- [x] Test bestaande inschrijving
- [x] Test iDeal

## Optioneel
- [x] Scherm voor toevoegen online bijles pakketten

**Comment by blackshadev** [comment]
Extra opmerkingen bij de inschrijving doen we nu nog niet, dat is verwarrend bij het inschrijf formulier omdat je dan 2 opmerkingen velden zou krijgen

**Comment by robinklaassen** [comment]
Closed with #84
